# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog-app
        image: europe-north1-docker.pkg.dev/fall-week7-1/hello-repo/helloworld-gke:latest
        ports:
        - containerPort: 80

---
# Blog App LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

